<?php
/**
 * StorefrontUsersApi
 * PHP version 7.2
 *
 * @category Class
 * @package  Aurigma\Storefront
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Storefront API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: storefront-v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Aurigma\Storefront\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Aurigma\Storefront\ApiException;
use Aurigma\Storefront\Configuration;
use Aurigma\Storefront\HeaderSelector;
use Aurigma\Storefront\ObjectSerializer;

/**
 * StorefrontUsersApi Class Doc Comment
 *
 * @category Class
 * @package  Aurigma\Storefront
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class StorefrontUsersApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation storefrontUsersCreate
     *
     * Creates new storefront user
     *
     * @param  int $storefront_id Storefront identifier (required)
     * @param  int $tenant_id Tenant identifier (optional)
     * @param  int $user_id User identifier (optional)
     * @param  \Aurigma\Storefront\Model\CreateStorefrontUserDto $create_storefront_user_dto Create operation parameters (optional)
     *
     * @throws \Aurigma\Storefront\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Aurigma\Storefront\Model\StorefrontUserDto
     */
    public function storefrontUsersCreate($storefront_id, $tenant_id = null, $user_id = null, $create_storefront_user_dto = null)
    {
        list($response) = $this->storefrontUsersCreateWithHttpInfo($storefront_id, $tenant_id, $user_id, $create_storefront_user_dto);
        return $response;
    }

    /**
     * Operation storefrontUsersCreateWithHttpInfo
     *
     * Creates new storefront user
     *
     * @param  int $storefront_id Storefront identifier (required)
     * @param  int $tenant_id Tenant identifier (optional)
     * @param  int $user_id User identifier (optional)
     * @param  \Aurigma\Storefront\Model\CreateStorefrontUserDto $create_storefront_user_dto Create operation parameters (optional)
     *
     * @throws \Aurigma\Storefront\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Aurigma\Storefront\Model\StorefrontUserDto, HTTP status code, HTTP response headers (array of strings)
     */
    public function storefrontUsersCreateWithHttpInfo($storefront_id, $tenant_id = null, $user_id = null, $create_storefront_user_dto = null)
    {
        $request = $this->storefrontUsersCreateRequest($storefront_id, $tenant_id, $user_id, $create_storefront_user_dto);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 201:
                    if ('\Aurigma\Storefront\Model\StorefrontUserDto' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Aurigma\Storefront\Model\StorefrontUserDto', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Aurigma\Storefront\Model\StorefrontUserDto';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Aurigma\Storefront\Model\StorefrontUserDto',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation storefrontUsersCreateAsync
     *
     * Creates new storefront user
     *
     * @param  int $storefront_id Storefront identifier (required)
     * @param  int $tenant_id Tenant identifier (optional)
     * @param  int $user_id User identifier (optional)
     * @param  \Aurigma\Storefront\Model\CreateStorefrontUserDto $create_storefront_user_dto Create operation parameters (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function storefrontUsersCreateAsync($storefront_id, $tenant_id = null, $user_id = null, $create_storefront_user_dto = null)
    {
        return $this->storefrontUsersCreateAsyncWithHttpInfo($storefront_id, $tenant_id, $user_id, $create_storefront_user_dto)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation storefrontUsersCreateAsyncWithHttpInfo
     *
     * Creates new storefront user
     *
     * @param  int $storefront_id Storefront identifier (required)
     * @param  int $tenant_id Tenant identifier (optional)
     * @param  int $user_id User identifier (optional)
     * @param  \Aurigma\Storefront\Model\CreateStorefrontUserDto $create_storefront_user_dto Create operation parameters (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function storefrontUsersCreateAsyncWithHttpInfo($storefront_id, $tenant_id = null, $user_id = null, $create_storefront_user_dto = null)
    {
        $returnType = '\Aurigma\Storefront\Model\StorefrontUserDto';
        $request = $this->storefrontUsersCreateRequest($storefront_id, $tenant_id, $user_id, $create_storefront_user_dto);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'storefrontUsersCreate'
     *
     * @param  int $storefront_id Storefront identifier (required)
     * @param  int $tenant_id Tenant identifier (optional)
     * @param  int $user_id User identifier (optional)
     * @param  \Aurigma\Storefront\Model\CreateStorefrontUserDto $create_storefront_user_dto Create operation parameters (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function storefrontUsersCreateRequest($storefront_id, $tenant_id = null, $user_id = null, $create_storefront_user_dto = null)
    {
        // verify the required parameter 'storefront_id' is set
        if ($storefront_id === null || (is_array($storefront_id) && count($storefront_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $storefront_id when calling storefrontUsersCreate'
            );
        }

        $resourcePath = '/api/storefront/v1/storefront-users';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($storefront_id !== null) {
            if('form' === 'form' && is_array($storefront_id)) {
                foreach($storefront_id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['storefrontId'] = $storefront_id;
            }
        }
        // query params
        if ($tenant_id !== null) {
            if('form' === 'form' && is_array($tenant_id)) {
                foreach($tenant_id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['tenantId'] = $tenant_id;
            }
        }
        // query params
        if ($user_id !== null) {
            if('form' === 'form' && is_array($user_id)) {
                foreach($user_id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['userId'] = $user_id;
            }
        }




        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['text/plain', 'application/json', 'text/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['text/plain', 'application/json', 'text/json'],
                ['application/json-patch+json', 'application/json', 'text/json', 'application/_*+json']
            );
        }

        // for model (json/xml)
        if (isset($create_storefront_user_dto)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($create_storefront_user_dto));
            } else {
                $httpBody = $create_storefront_user_dto;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        // aurigmafix 6
                        if (gettype($formParamValueItem) === 'object') {
                            if (!($formParamValueItem instanceof StreamInterface 
                            || $formParamValueItem instanceof \Iterator 
                            || method_exists($formParamValueItem, '__toString'))) {
                                $formParamValueItem = json_encode($formParamValueItem);
                            }
                        } 
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }
        // this endpoint requires OAuth (access token)
        // aurigmafix 3
        $token = $this->config->getAccessToken();
        if ($token !== null && $token !== '' && !ctype_space($token)) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation storefrontUsersGet
     *
     * Gets storefront user by id
     *
     * @param  string $id Storefront user identifier (required)
     * @param  int $storefront_id Storefront identifier (required)
     * @param  int $tenant_id Tenant identifier (optional)
     * @param  int $user_id User identifier (optional)
     *
     * @throws \Aurigma\Storefront\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Aurigma\Storefront\Model\StorefrontUserDto|\Aurigma\Storefront\Model\MicrosoftAspNetCoreMvcProblemDetails
     */
    public function storefrontUsersGet($id, $storefront_id, $tenant_id = null, $user_id = null)
    {
        list($response) = $this->storefrontUsersGetWithHttpInfo($id, $storefront_id, $tenant_id, $user_id);
        return $response;
    }

    /**
     * Operation storefrontUsersGetWithHttpInfo
     *
     * Gets storefront user by id
     *
     * @param  string $id Storefront user identifier (required)
     * @param  int $storefront_id Storefront identifier (required)
     * @param  int $tenant_id Tenant identifier (optional)
     * @param  int $user_id User identifier (optional)
     *
     * @throws \Aurigma\Storefront\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Aurigma\Storefront\Model\StorefrontUserDto|\Aurigma\Storefront\Model\MicrosoftAspNetCoreMvcProblemDetails, HTTP status code, HTTP response headers (array of strings)
     */
    public function storefrontUsersGetWithHttpInfo($id, $storefront_id, $tenant_id = null, $user_id = null)
    {
        $request = $this->storefrontUsersGetRequest($id, $storefront_id, $tenant_id, $user_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Aurigma\Storefront\Model\StorefrontUserDto' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Aurigma\Storefront\Model\StorefrontUserDto', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\Aurigma\Storefront\Model\MicrosoftAspNetCoreMvcProblemDetails' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Aurigma\Storefront\Model\MicrosoftAspNetCoreMvcProblemDetails', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Aurigma\Storefront\Model\StorefrontUserDto';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Aurigma\Storefront\Model\StorefrontUserDto',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Aurigma\Storefront\Model\MicrosoftAspNetCoreMvcProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation storefrontUsersGetAsync
     *
     * Gets storefront user by id
     *
     * @param  string $id Storefront user identifier (required)
     * @param  int $storefront_id Storefront identifier (required)
     * @param  int $tenant_id Tenant identifier (optional)
     * @param  int $user_id User identifier (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function storefrontUsersGetAsync($id, $storefront_id, $tenant_id = null, $user_id = null)
    {
        return $this->storefrontUsersGetAsyncWithHttpInfo($id, $storefront_id, $tenant_id, $user_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation storefrontUsersGetAsyncWithHttpInfo
     *
     * Gets storefront user by id
     *
     * @param  string $id Storefront user identifier (required)
     * @param  int $storefront_id Storefront identifier (required)
     * @param  int $tenant_id Tenant identifier (optional)
     * @param  int $user_id User identifier (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function storefrontUsersGetAsyncWithHttpInfo($id, $storefront_id, $tenant_id = null, $user_id = null)
    {
        $returnType = '\Aurigma\Storefront\Model\StorefrontUserDto';
        $request = $this->storefrontUsersGetRequest($id, $storefront_id, $tenant_id, $user_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'storefrontUsersGet'
     *
     * @param  string $id Storefront user identifier (required)
     * @param  int $storefront_id Storefront identifier (required)
     * @param  int $tenant_id Tenant identifier (optional)
     * @param  int $user_id User identifier (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function storefrontUsersGetRequest($id, $storefront_id, $tenant_id = null, $user_id = null)
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling storefrontUsersGet'
            );
        }
        // verify the required parameter 'storefront_id' is set
        if ($storefront_id === null || (is_array($storefront_id) && count($storefront_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $storefront_id when calling storefrontUsersGet'
            );
        }

        $resourcePath = '/api/storefront/v1/storefront-users/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($storefront_id !== null) {
            if('form' === 'form' && is_array($storefront_id)) {
                foreach($storefront_id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['storefrontId'] = $storefront_id;
            }
        }
        // query params
        if ($tenant_id !== null) {
            if('form' === 'form' && is_array($tenant_id)) {
                foreach($tenant_id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['tenantId'] = $tenant_id;
            }
        }
        // query params
        if ($user_id !== null) {
            if('form' === 'form' && is_array($user_id)) {
                foreach($user_id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['userId'] = $user_id;
            }
        }


        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['text/plain', 'application/json', 'text/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['text/plain', 'application/json', 'text/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        // aurigmafix 6
                        if (gettype($formParamValueItem) === 'object') {
                            if (!($formParamValueItem instanceof StreamInterface 
                            || $formParamValueItem instanceof \Iterator 
                            || method_exists($formParamValueItem, '__toString'))) {
                                $formParamValueItem = json_encode($formParamValueItem);
                            }
                        } 
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }
        // this endpoint requires OAuth (access token)
        // aurigmafix 3
        $token = $this->config->getAccessToken();
        if ($token !== null && $token !== '' && !ctype_space($token)) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation storefrontUsersGetAll
     *
     * Gets all storefront users relevant to specified query parameters
     *
     * @param  int $storefront_id Storefront identifier (required)
     * @param  string $storefront_user_id Storefront user identifier (optional)
     * @param  int $skip Defines page start offset from beginning of sorted result list (optional)
     * @param  int $take Defines page length (how much consequent items of sorted result list should be taken) (optional)
     * @param  string $sorting Defines sorting order of result list e.g.: \&quot;Title ASC, LastModified DESC\&quot; (optional)
     * @param  string $search Search string for partial match (optional)
     * @param  int $tenant_id Tenant identifier (optional)
     * @param  int $user_id User identifier (optional)
     *
     * @throws \Aurigma\Storefront\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Aurigma\Storefront\Model\PagedOfStorefrontUserDto
     */
    public function storefrontUsersGetAll($storefront_id, $storefront_user_id = null, $skip = null, $take = null, $sorting = null, $search = null, $tenant_id = null, $user_id = null)
    {
        list($response) = $this->storefrontUsersGetAllWithHttpInfo($storefront_id, $storefront_user_id, $skip, $take, $sorting, $search, $tenant_id, $user_id);
        return $response;
    }

    /**
     * Operation storefrontUsersGetAllWithHttpInfo
     *
     * Gets all storefront users relevant to specified query parameters
     *
     * @param  int $storefront_id Storefront identifier (required)
     * @param  string $storefront_user_id Storefront user identifier (optional)
     * @param  int $skip Defines page start offset from beginning of sorted result list (optional)
     * @param  int $take Defines page length (how much consequent items of sorted result list should be taken) (optional)
     * @param  string $sorting Defines sorting order of result list e.g.: \&quot;Title ASC, LastModified DESC\&quot; (optional)
     * @param  string $search Search string for partial match (optional)
     * @param  int $tenant_id Tenant identifier (optional)
     * @param  int $user_id User identifier (optional)
     *
     * @throws \Aurigma\Storefront\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Aurigma\Storefront\Model\PagedOfStorefrontUserDto, HTTP status code, HTTP response headers (array of strings)
     */
    public function storefrontUsersGetAllWithHttpInfo($storefront_id, $storefront_user_id = null, $skip = null, $take = null, $sorting = null, $search = null, $tenant_id = null, $user_id = null)
    {
        $request = $this->storefrontUsersGetAllRequest($storefront_id, $storefront_user_id, $skip, $take, $sorting, $search, $tenant_id, $user_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Aurigma\Storefront\Model\PagedOfStorefrontUserDto' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Aurigma\Storefront\Model\PagedOfStorefrontUserDto', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Aurigma\Storefront\Model\PagedOfStorefrontUserDto';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Aurigma\Storefront\Model\PagedOfStorefrontUserDto',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation storefrontUsersGetAllAsync
     *
     * Gets all storefront users relevant to specified query parameters
     *
     * @param  int $storefront_id Storefront identifier (required)
     * @param  string $storefront_user_id Storefront user identifier (optional)
     * @param  int $skip Defines page start offset from beginning of sorted result list (optional)
     * @param  int $take Defines page length (how much consequent items of sorted result list should be taken) (optional)
     * @param  string $sorting Defines sorting order of result list e.g.: \&quot;Title ASC, LastModified DESC\&quot; (optional)
     * @param  string $search Search string for partial match (optional)
     * @param  int $tenant_id Tenant identifier (optional)
     * @param  int $user_id User identifier (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function storefrontUsersGetAllAsync($storefront_id, $storefront_user_id = null, $skip = null, $take = null, $sorting = null, $search = null, $tenant_id = null, $user_id = null)
    {
        return $this->storefrontUsersGetAllAsyncWithHttpInfo($storefront_id, $storefront_user_id, $skip, $take, $sorting, $search, $tenant_id, $user_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation storefrontUsersGetAllAsyncWithHttpInfo
     *
     * Gets all storefront users relevant to specified query parameters
     *
     * @param  int $storefront_id Storefront identifier (required)
     * @param  string $storefront_user_id Storefront user identifier (optional)
     * @param  int $skip Defines page start offset from beginning of sorted result list (optional)
     * @param  int $take Defines page length (how much consequent items of sorted result list should be taken) (optional)
     * @param  string $sorting Defines sorting order of result list e.g.: \&quot;Title ASC, LastModified DESC\&quot; (optional)
     * @param  string $search Search string for partial match (optional)
     * @param  int $tenant_id Tenant identifier (optional)
     * @param  int $user_id User identifier (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function storefrontUsersGetAllAsyncWithHttpInfo($storefront_id, $storefront_user_id = null, $skip = null, $take = null, $sorting = null, $search = null, $tenant_id = null, $user_id = null)
    {
        $returnType = '\Aurigma\Storefront\Model\PagedOfStorefrontUserDto';
        $request = $this->storefrontUsersGetAllRequest($storefront_id, $storefront_user_id, $skip, $take, $sorting, $search, $tenant_id, $user_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'storefrontUsersGetAll'
     *
     * @param  int $storefront_id Storefront identifier (required)
     * @param  string $storefront_user_id Storefront user identifier (optional)
     * @param  int $skip Defines page start offset from beginning of sorted result list (optional)
     * @param  int $take Defines page length (how much consequent items of sorted result list should be taken) (optional)
     * @param  string $sorting Defines sorting order of result list e.g.: \&quot;Title ASC, LastModified DESC\&quot; (optional)
     * @param  string $search Search string for partial match (optional)
     * @param  int $tenant_id Tenant identifier (optional)
     * @param  int $user_id User identifier (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function storefrontUsersGetAllRequest($storefront_id, $storefront_user_id = null, $skip = null, $take = null, $sorting = null, $search = null, $tenant_id = null, $user_id = null)
    {
        // verify the required parameter 'storefront_id' is set
        if ($storefront_id === null || (is_array($storefront_id) && count($storefront_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $storefront_id when calling storefrontUsersGetAll'
            );
        }

        $resourcePath = '/api/storefront/v1/storefront-users';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($storefront_user_id !== null) {
            if('form' === 'form' && is_array($storefront_user_id)) {
                foreach($storefront_user_id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['storefrontUserId'] = $storefront_user_id;
            }
        }
        // query params
        if ($skip !== null) {
            if('form' === 'form' && is_array($skip)) {
                foreach($skip as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['skip'] = $skip;
            }
        }
        // query params
        if ($take !== null) {
            if('form' === 'form' && is_array($take)) {
                foreach($take as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['take'] = $take;
            }
        }
        // query params
        if ($sorting !== null) {
            if('form' === 'form' && is_array($sorting)) {
                foreach($sorting as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['sorting'] = $sorting;
            }
        }
        // query params
        if ($search !== null) {
            if('form' === 'form' && is_array($search)) {
                foreach($search as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['search'] = $search;
            }
        }
        // query params
        if ($storefront_id !== null) {
            if('form' === 'form' && is_array($storefront_id)) {
                foreach($storefront_id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['storefrontId'] = $storefront_id;
            }
        }
        // query params
        if ($tenant_id !== null) {
            if('form' === 'form' && is_array($tenant_id)) {
                foreach($tenant_id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['tenantId'] = $tenant_id;
            }
        }
        // query params
        if ($user_id !== null) {
            if('form' === 'form' && is_array($user_id)) {
                foreach($user_id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['userId'] = $user_id;
            }
        }




        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['text/plain', 'application/json', 'text/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['text/plain', 'application/json', 'text/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        // aurigmafix 6
                        if (gettype($formParamValueItem) === 'object') {
                            if (!($formParamValueItem instanceof StreamInterface 
                            || $formParamValueItem instanceof \Iterator 
                            || method_exists($formParamValueItem, '__toString'))) {
                                $formParamValueItem = json_encode($formParamValueItem);
                            }
                        } 
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }
        // this endpoint requires OAuth (access token)
        // aurigmafix 3
        $token = $this->config->getAccessToken();
        if ($token !== null && $token !== '' && !ctype_space($token)) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation storefrontUsersGetToken
     *
     * Gets storefront user token
     *
     * @param  string $storefront_user_id Storefront user identifier (required)
     * @param  int $storefront_id Storefront identifier (required)
     * @param  int $tenant_id Tenant identifier (optional)
     * @param  int $user_id User identifier (optional)
     *
     * @throws \Aurigma\Storefront\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function storefrontUsersGetToken($storefront_user_id, $storefront_id, $tenant_id = null, $user_id = null)
    {
        $this->storefrontUsersGetTokenWithHttpInfo($storefront_user_id, $storefront_id, $tenant_id, $user_id);
    }

    /**
     * Operation storefrontUsersGetTokenWithHttpInfo
     *
     * Gets storefront user token
     *
     * @param  string $storefront_user_id Storefront user identifier (required)
     * @param  int $storefront_id Storefront identifier (required)
     * @param  int $tenant_id Tenant identifier (optional)
     * @param  int $user_id User identifier (optional)
     *
     * @throws \Aurigma\Storefront\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function storefrontUsersGetTokenWithHttpInfo($storefront_user_id, $storefront_id, $tenant_id = null, $user_id = null)
    {
        $request = $this->storefrontUsersGetTokenRequest($storefront_user_id, $storefront_id, $tenant_id, $user_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Aurigma\Storefront\Model\MicrosoftAspNetCoreMvcProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Aurigma\Storefront\Model\MicrosoftAspNetCoreMvcProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation storefrontUsersGetTokenAsync
     *
     * Gets storefront user token
     *
     * @param  string $storefront_user_id Storefront user identifier (required)
     * @param  int $storefront_id Storefront identifier (required)
     * @param  int $tenant_id Tenant identifier (optional)
     * @param  int $user_id User identifier (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function storefrontUsersGetTokenAsync($storefront_user_id, $storefront_id, $tenant_id = null, $user_id = null)
    {
        return $this->storefrontUsersGetTokenAsyncWithHttpInfo($storefront_user_id, $storefront_id, $tenant_id, $user_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation storefrontUsersGetTokenAsyncWithHttpInfo
     *
     * Gets storefront user token
     *
     * @param  string $storefront_user_id Storefront user identifier (required)
     * @param  int $storefront_id Storefront identifier (required)
     * @param  int $tenant_id Tenant identifier (optional)
     * @param  int $user_id User identifier (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function storefrontUsersGetTokenAsyncWithHttpInfo($storefront_user_id, $storefront_id, $tenant_id = null, $user_id = null)
    {
        $returnType = '';
        $request = $this->storefrontUsersGetTokenRequest($storefront_user_id, $storefront_id, $tenant_id, $user_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'storefrontUsersGetToken'
     *
     * @param  string $storefront_user_id Storefront user identifier (required)
     * @param  int $storefront_id Storefront identifier (required)
     * @param  int $tenant_id Tenant identifier (optional)
     * @param  int $user_id User identifier (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function storefrontUsersGetTokenRequest($storefront_user_id, $storefront_id, $tenant_id = null, $user_id = null)
    {
        // verify the required parameter 'storefront_user_id' is set
        if ($storefront_user_id === null || (is_array($storefront_user_id) && count($storefront_user_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $storefront_user_id when calling storefrontUsersGetToken'
            );
        }
        // verify the required parameter 'storefront_id' is set
        if ($storefront_id === null || (is_array($storefront_id) && count($storefront_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $storefront_id when calling storefrontUsersGetToken'
            );
        }

        $resourcePath = '/api/storefront/v1/storefront-users/token';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($storefront_user_id !== null) {
            if('form' === 'form' && is_array($storefront_user_id)) {
                foreach($storefront_user_id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['storefrontUserId'] = $storefront_user_id;
            }
        }
        // query params
        if ($storefront_id !== null) {
            if('form' === 'form' && is_array($storefront_id)) {
                foreach($storefront_id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['storefrontId'] = $storefront_id;
            }
        }
        // query params
        if ($tenant_id !== null) {
            if('form' === 'form' && is_array($tenant_id)) {
                foreach($tenant_id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['tenantId'] = $tenant_id;
            }
        }
        // query params
        if ($user_id !== null) {
            if('form' === 'form' && is_array($user_id)) {
                foreach($user_id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['userId'] = $user_id;
            }
        }




        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['text/plain', 'application/json', 'text/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['text/plain', 'application/json', 'text/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        // aurigmafix 6
                        if (gettype($formParamValueItem) === 'object') {
                            if (!($formParamValueItem instanceof StreamInterface 
                            || $formParamValueItem instanceof \Iterator 
                            || method_exists($formParamValueItem, '__toString'))) {
                                $formParamValueItem = json_encode($formParamValueItem);
                            }
                        } 
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }
        // this endpoint requires OAuth (access token)
        // aurigmafix 3
        $token = $this->config->getAccessToken();
        if ($token !== null && $token !== '' && !ctype_space($token)) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation storefrontUsersMergeAnonymous
     *
     * Merges anonymous storefront user data to regular storefront user account
     *
     * @param  int $storefront_id Storefront identifier (required)
     * @param  int $tenant_id Tenant identifier (optional)
     * @param  int $user_id User identifier (optional)
     * @param  \Aurigma\Storefront\Model\MergeAnonymousUserDataInput $merge_anonymous_user_data_input Merge operation parameters (optional)
     *
     * @throws \Aurigma\Storefront\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function storefrontUsersMergeAnonymous($storefront_id, $tenant_id = null, $user_id = null, $merge_anonymous_user_data_input = null)
    {
        $this->storefrontUsersMergeAnonymousWithHttpInfo($storefront_id, $tenant_id, $user_id, $merge_anonymous_user_data_input);
    }

    /**
     * Operation storefrontUsersMergeAnonymousWithHttpInfo
     *
     * Merges anonymous storefront user data to regular storefront user account
     *
     * @param  int $storefront_id Storefront identifier (required)
     * @param  int $tenant_id Tenant identifier (optional)
     * @param  int $user_id User identifier (optional)
     * @param  \Aurigma\Storefront\Model\MergeAnonymousUserDataInput $merge_anonymous_user_data_input Merge operation parameters (optional)
     *
     * @throws \Aurigma\Storefront\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function storefrontUsersMergeAnonymousWithHttpInfo($storefront_id, $tenant_id = null, $user_id = null, $merge_anonymous_user_data_input = null)
    {
        $request = $this->storefrontUsersMergeAnonymousRequest($storefront_id, $tenant_id, $user_id, $merge_anonymous_user_data_input);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Aurigma\Storefront\Model\MicrosoftAspNetCoreMvcProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Aurigma\Storefront\Model\MicrosoftAspNetCoreMvcProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation storefrontUsersMergeAnonymousAsync
     *
     * Merges anonymous storefront user data to regular storefront user account
     *
     * @param  int $storefront_id Storefront identifier (required)
     * @param  int $tenant_id Tenant identifier (optional)
     * @param  int $user_id User identifier (optional)
     * @param  \Aurigma\Storefront\Model\MergeAnonymousUserDataInput $merge_anonymous_user_data_input Merge operation parameters (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function storefrontUsersMergeAnonymousAsync($storefront_id, $tenant_id = null, $user_id = null, $merge_anonymous_user_data_input = null)
    {
        return $this->storefrontUsersMergeAnonymousAsyncWithHttpInfo($storefront_id, $tenant_id, $user_id, $merge_anonymous_user_data_input)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation storefrontUsersMergeAnonymousAsyncWithHttpInfo
     *
     * Merges anonymous storefront user data to regular storefront user account
     *
     * @param  int $storefront_id Storefront identifier (required)
     * @param  int $tenant_id Tenant identifier (optional)
     * @param  int $user_id User identifier (optional)
     * @param  \Aurigma\Storefront\Model\MergeAnonymousUserDataInput $merge_anonymous_user_data_input Merge operation parameters (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function storefrontUsersMergeAnonymousAsyncWithHttpInfo($storefront_id, $tenant_id = null, $user_id = null, $merge_anonymous_user_data_input = null)
    {
        $returnType = '';
        $request = $this->storefrontUsersMergeAnonymousRequest($storefront_id, $tenant_id, $user_id, $merge_anonymous_user_data_input);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'storefrontUsersMergeAnonymous'
     *
     * @param  int $storefront_id Storefront identifier (required)
     * @param  int $tenant_id Tenant identifier (optional)
     * @param  int $user_id User identifier (optional)
     * @param  \Aurigma\Storefront\Model\MergeAnonymousUserDataInput $merge_anonymous_user_data_input Merge operation parameters (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function storefrontUsersMergeAnonymousRequest($storefront_id, $tenant_id = null, $user_id = null, $merge_anonymous_user_data_input = null)
    {
        // verify the required parameter 'storefront_id' is set
        if ($storefront_id === null || (is_array($storefront_id) && count($storefront_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $storefront_id when calling storefrontUsersMergeAnonymous'
            );
        }

        $resourcePath = '/api/storefront/v1/storefront-users/merge-anonymous';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($storefront_id !== null) {
            if('form' === 'form' && is_array($storefront_id)) {
                foreach($storefront_id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['storefrontId'] = $storefront_id;
            }
        }
        // query params
        if ($tenant_id !== null) {
            if('form' === 'form' && is_array($tenant_id)) {
                foreach($tenant_id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['tenantId'] = $tenant_id;
            }
        }
        // query params
        if ($user_id !== null) {
            if('form' === 'form' && is_array($user_id)) {
                foreach($user_id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['userId'] = $user_id;
            }
        }




        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['text/plain', 'application/json', 'text/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['text/plain', 'application/json', 'text/json'],
                ['application/json-patch+json', 'application/json', 'text/json', 'application/_*+json']
            );
        }

        // for model (json/xml)
        if (isset($merge_anonymous_user_data_input)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($merge_anonymous_user_data_input));
            } else {
                $httpBody = $merge_anonymous_user_data_input;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        // aurigmafix 6
                        if (gettype($formParamValueItem) === 'object') {
                            if (!($formParamValueItem instanceof StreamInterface 
                            || $formParamValueItem instanceof \Iterator 
                            || method_exists($formParamValueItem, '__toString'))) {
                                $formParamValueItem = json_encode($formParamValueItem);
                            }
                        } 
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }
        // this endpoint requires OAuth (access token)
        // aurigmafix 3
        $token = $this->config->getAccessToken();
        if ($token !== null && $token !== '' && !ctype_space($token)) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
