<?php
/**
 * ConflictType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurigma\Storefront
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Storefront API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: storefront-v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Aurigma\Storefront\Model;
use \Aurigma\Storefront\ObjectSerializer;

/**
 * ConflictType Class Doc Comment
 *
 * @category Class
 * @description Conflict types.
 * @package  Aurigma\Storefront
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ConflictType
{
    /**
     * Possible values of this enum
     */
    public const NAME_CONFLICT = 'NameConflict';

    public const FOLDER_OVERWRITE_CONFLICT = 'FolderOverwriteConflict';

    public const ID_CONFLICT = 'IdConflict';

    public const GENERAL_CONFLICT = 'GeneralConflict';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NAME_CONFLICT,
            self::FOLDER_OVERWRITE_CONFLICT,
            self::ID_CONFLICT,
            self::GENERAL_CONFLICT
        ];
    }
}


