<?php
/**
 * RenderHiResScenarioOutputRotateMode
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurigma\Storefront
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Storefront API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: storefront-v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Aurigma\Storefront\Model;
use \Aurigma\Storefront\ObjectSerializer;

/**
 * RenderHiResScenarioOutputRotateMode Class Doc Comment
 *
 * @category Class
 * @package  Aurigma\Storefront
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class RenderHiResScenarioOutputRotateMode
{
    /**
     * Possible values of this enum
     */
    public const NONE = 'None';

    public const ROTATE90 = 'Rotate90';

    public const ROTATE180 = 'Rotate180';

    public const ROTATE270 = 'Rotate270';

    public const AUTO = 'Auto';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NONE,
            self::ROTATE90,
            self::ROTATE180,
            self::ROTATE270,
            self::AUTO
        ];
    }
}


