<?php
/**
 * ProductVariantOptionDtoTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurigma\Storefront
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Storefront API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: storefront-v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Aurigma\Storefront\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ProductVariantOptionDtoTest Class Doc Comment
 *
 * @category    Class
 * @description DTO class, containing information about a product variant option.
 * @package     Aurigma\Storefront
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ProductVariantOptionDtoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ProductVariantOptionDto"
     */
    public function testProductVariantOptionDto()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "product_option_id"
     */
    public function testPropertyProductOptionId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "product_option_value_id"
     */
    public function testPropertyProductOptionValueId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "product_option_type"
     */
    public function testPropertyProductOptionType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "product_option_traits"
     */
    public function testPropertyProductOptionTraits()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "product_option_title"
     */
    public function testPropertyProductOptionTitle()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "product_option_value_title"
     */
    public function testPropertyProductOptionValueTitle()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "simple_option_value"
     */
    public function testPropertySimpleOptionValue()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
