<?php
/**
 * WorkflowTypeTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurigma\Storefront
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Storefront API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: storefront-v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Aurigma\Storefront\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * WorkflowTypeTest Class Doc Comment
 *
 * @category    Class
 * @description Type of editor that should be configured by workflow.
 * @package     Aurigma\Storefront
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class WorkflowTypeTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "WorkflowType"
     */
    public function testWorkflowType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
