<?php
/**
 * ProcessingPipelinesApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurigma\Storefront
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Storefront API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: storefront-v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Aurigma\Storefront\Test\Api;

use \Aurigma\Storefront\Configuration;
use \Aurigma\Storefront\ApiException;
use \Aurigma\Storefront\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ProcessingPipelinesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Aurigma\Storefront
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProcessingPipelinesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for processingPipelinesGet
     *
     * Returns a processing pipeline..
     *
     */
    public function testProcessingPipelinesGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for processingPipelinesGetAll
     *
     * Returns all processing pipelines relevant to the specified query parameters..
     *
     */
    public function testProcessingPipelinesGetAll()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
