<?php
/**
 * ProductsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurigma\Storefront
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Storefront API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: storefront-v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Aurigma\Storefront\Test\Api;

use \Aurigma\Storefront\Configuration;
use \Aurigma\Storefront\ApiException;
use \Aurigma\Storefront\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ProductsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Aurigma\Storefront
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProductsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for productsGetAllProductOptions
     *
     * Returns a list of product options for all products..
     *
     */
    public function testProductsGetAllProductOptions()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productsGetAllProducts
     *
     * Returns all products, relevant to the specified query parameters..
     *
     */
    public function testProductsGetAllProducts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productsGetAvailableProductTags
     *
     * Returns a list of all available product tags..
     *
     */
    public function testProductsGetAvailableProductTags()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productsGetPersonalizationWorkflow
     *
     * Returns a product personalization workflow description by product identifier..
     *
     */
    public function testProductsGetPersonalizationWorkflow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productsGetProduct
     *
     * Returns a product by identifier..
     *
     */
    public function testProductsGetProduct()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productsGetProductLink
     *
     * Returns a product link..
     *
     */
    public function testProductsGetProductLink()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productsGetProductLinks
     *
     * Returns a list of product links..
     *
     */
    public function testProductsGetProductLinks()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productsGetProductOptions
     *
     * Returns a list of product options..
     *
     */
    public function testProductsGetProductOptions()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productsGetProductSummary
     *
     * Returns a product summary by product identifier..
     *
     */
    public function testProductsGetProductSummary()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productsGetProductVariant
     *
     * Returns a product variant..
     *
     */
    public function testProductsGetProductVariant()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productsGetProductVariantDesigns
     *
     * Returns a list of product variant designs..
     *
     */
    public function testProductsGetProductVariantDesigns()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productsGetProductVariantDocuments
     *
     * Returns a list of product variant documents..
     *
     */
    public function testProductsGetProductVariantDocuments()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productsGetProductVariantMockups
     *
     * Returns a list of product variant mockups..
     *
     */
    public function testProductsGetProductVariantMockups()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productsGetProductVariants
     *
     * Returns a list of product variants..
     *
     */
    public function testProductsGetProductVariants()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productsUpdateProductVariantResources
     *
     * Updates product variant resources..
     *
     */
    public function testProductsUpdateProductVariantResources()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
