<?php
/**
 * ProductReferencesApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  Aurigma\Storefront
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Storefront API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: storefront-v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Aurigma\Storefront\Test\Api;

use \Aurigma\Storefront\Configuration;
use \Aurigma\Storefront\ApiException;
use \Aurigma\Storefront\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ProductReferencesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Aurigma\Storefront
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProductReferencesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for productReferencesCreate
     *
     * Creates new storefront product reference.
     *
     */
    public function testProductReferencesCreate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productReferencesDelete
     *
     * Deletes storefront product reference.
     *
     */
    public function testProductReferencesDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productReferencesGet
     *
     * Gets storefront product reference.
     *
     */
    public function testProductReferencesGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productReferencesGetAll
     *
     * Gets all storefront product references relevant to specified query parameters.
     *
     */
    public function testProductReferencesGetAll()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productReferencesGetProductConfig
     *
     * Gets product configuration information by storefront product reference.
     *
     */
    public function testProductReferencesGetProductConfig()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productReferencesGetProductSpecification
     *
     * Gets product specification by storefront product reference.
     *
     */
    public function testProductReferencesGetProductSpecification()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
